#[[plugins]]
#repo = 'billyvg/tigris.nvim'
#on_ft = ['javascript', 'javascript.jsx']
#hook_post_update = '''
#  let g:dein#plugin.build = './install.sh'
#  let g:tigris#enabled = 1
#  let g:tigris#on_the_fly_enabled = 1
#  let g:tigris#delay = 500
#'''
#
#[[plugins]]
#repo = 'leafgarland/typescript-vim'
#
#[[plugins]]
#repo = 'peitalin/vim-jsx-typescript'

